### ISSUE TITLE
Bringing back Cairo v0 docs

### ISSUE THREAD

**Issue by 9oelM** [astraly-labs/pragma-docs#19]
Hi there. I'm Joel working @zklend. I've got a little request, which is to bring back the Cairo v0 docs. The main reason is that sometimes you need to look at the historical data in the past to obtain useful information for analytics, etc. For example, I can't easily confirm if the number of decimal places used for USDT/USD is the same for v1 and v0. But this would be an useful and necessary piece of information if I am writing a subgraph that indexes data from Pragma (back then, Empiric) v0 and v1 to use it for @zklend. 

But without Cairo v0 docs, it's quite troublesome to navigate how the oracle was before. I know I can go back on git and have a look at it again or use [Wayback machine](https://archive.org/web/), but I just wanted to put it out there so you guys can know about this use case, and also just being able to look it up on your website would make the whole thing a lot easier.

**Comment by EvolveArt** [comment]
> Hi there. I'm Joel working @zklend. I've got a little request, which is to bring back the Cairo v0 docs. The main reason is that sometimes you need to look at the historical data in the past to obtain useful information for analytics, etc. For example, I can't easily confirm if the number of decimal places used for USDT/USD is the same for v1 and v0. But this would be an useful and necessary piece of information if I am writing a subgraph that indexes data from Pragma (back then, Empiric) v0 and v1 to use it for @zklend. 
> 
> 
> 
> But without Cairo v0 docs, it's quite troublesome to navigate how the oracle was before. I know I can go back on git and have a look at it again or use [Wayback machine](https://archive.org/web/), but I just wanted to put it out there so you guys can know about this use case, and also just being able to look it up on your website would make the whole thing a lot easier.
> 
> 

Hey! Sure will bring it back 🫡

**Comment by 9oelM** [comment]
> > Hi there. I'm Joel working @zkLend. I've got a little request, which is to bring back the Cairo v0 docs. The main reason is that sometimes you need to look at the historical data in the past to obtain useful information for analytics, etc. For example, I can't easily confirm if the number of decimal places used for USDT/USD is the same for v1 and v0. But this would be an useful and necessary piece of information if I am writing a subgraph that indexes data from Pragma (back then, Empiric) v0 and v1 to use it for @zkLend.
> > But without Cairo v0 docs, it's quite troublesome to navigate how the oracle was before. I know I can go back on git and have a look at it again or use [Wayback machine](https://archive.org/web/), but I just wanted to put it out there so you guys can know about this use case, and also just being able to look it up on your website would make the whole thing a lot easier.
> 
> Hey! Sure will bring it back 🫡

Thanks! 🙏🏼
